name: Deploy Github Pages

on:
  push:
    branches:
      - main
      - work

jobs:
  deploy-github-demo:
    uses: ./.github/workflows/deploy-github-demo.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  deploy-github-docs:
    uses: ./.github/workflows/deploy-github-docs.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
