name: Test

on:
  push:
  pull_request:
    branches:
      - main
      - work

jobs:
  test-demos:
    uses: ./.github/workflows/demo-test.yml

  linter-and-unit:
    uses: ./.github/workflows/linter-and-unit-test.yml
